import * as InputTypes from "./Core.js";
export const CurrentPlanListSelector = "#SwitchingCurrentPlansListPopUp",
  CurrentPlanEditorSelector = "#EditCurrentPlanPopup",
  BasicDetails = {
    ProductID: {
      Selector: ".Product_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    Provider: {
      Selector: ".Provider",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    TransactKey: {
      Selector: ".TransactKey_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    AccountNo: {
      Selector: ".FundsNetworkAccountNumber_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    CurrentPlanName: {
      Selector: ".ProductName_tooltip input",
      inputType: InputTypes.Input_String ,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    DrawdownType: {
      Selector: ".Drawdown_DrawdownType_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    IncludeinConsolidatedReport: {
      Selector: ".InclConsolidatedReport",
      inputType:  InputTypes.Input_Checkbox,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
    Isworkplacepension: {
      Selector: "IsWorkplacePension",
      inputType: InputTypes.Input_Checkbox,
      AccordianName: "Basic Details",
      AccordianSelector: ".BasicDetailsAccordian",
    },
  },
  //As At Date doesnt have the dd mm yyyy simple control
  CurrentValue = {
    CurrentValue: {
      Selector: ".PolicyValuesCurrentValue_tooltip input",
      inputType: InputTypes.Input_Integer ,
      AccordianName: "Current Value",
      AccordianSelector: ".CurrentValueAccordian",
    },
    TransferValue: {
      Selector: ".PolicyValuesTransferValue_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Current Value",
      AccordianSelector: ".CurrentValueAccordian",
    },
    PotentialTaxDue: {
      Selector: ".PotentialTax_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Current Value",
      AccordianSelector: ".CurrentValueAccordian",
    },
  },
  DrawdownIncome = {
    DDI_NextGadReview: {
      Selector: ".Drawdown_GAD_Date_tooltip input",
      ddSelector: ".Drawdown_GAD_Date.day",
      mmSelector: ".Drawdown_GAD_Date.month",
      yyyySelector: ".Drawdown_GAD_Date.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeBasis: {
      Selector: ".Drawdown_IncomeType_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeAmount: {
      Selector: ".Drawdown_IncomeAmount_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomePercentage: {
      Selector: ".Drawdown_IncomePercentage_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_CurrentIncome: {
      Selector: ".Drawdown_CurrentIncome_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeStarting: {
      Selector: ".Drawdown_IncomeStarting_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeAge: {
      Selector: ".Drawdown_IncomeCommencementAge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeStarting: {
      Selector: ".Drawdown_IncomeFrequency_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeEscalation: {
      Selector: ".Drawdown_IncomeEscalation_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeOtherEscalation: {
      Selector: ".Drawdown_IncomeEscalationRateMid_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
    DDI_IncomeAnniversary: {
      Selector: ".Drawdown_IncomeAnniversary_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".DrawdownIncomeAccordian",
      AccordianName: "Drawdown Income",
    },
  },
  SuppliedMaturityValues = {
    SMV_Drawdown_MaturityValuesProjected: {
      Selector: ".DrawdownMaturityValuesProjected ",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_Drawdown_AnnuitisationAge: {
      Selector: ".Drawdown_AnnuitisationAge_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_Drawdown_TermYears: {
      Selector: ".Drawdown_TermYears_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_ProjectedMaturityValueBasis: {
      Selector: ".ProjectedMaturityBasis_tooltip input ",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_RetirementMaturityAge: {
      Selector: ".RetirementAge_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_TermYears: {
      Selector: ".TermYears_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_AMC: {
      Selector: ".EstimatedBySystemAMC_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_LowRateMaturityValue: {
      Selector: ".MaturityValueLow_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_MidRateMaturityValue: {
      Selector: ".MaturityValueMid_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_HighRateMaturityValue: {
      Selector: ".MaturityValueHigh_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_FundCharge: {
      Selector: ".SuppliedMaturityValuesAccordian .FundCharge_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_PlanCharge: {
      Selector: ".SuppliedMaturityValuesAccordian .PlanCharge_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_PolicyFee: {
      Selector: ".SuppliedMaturityValuesAccordian .PolicyFee_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
    SMV_AdviserCharge: {
      Selector: ".SuppliedMaturityValuesAccordian .AdviserCharge_tooltip input ",
      inputType: InputTypes.Input_Integer,
      AccordianName: "Supplied Maturity Values",
      AccordianSelector: ".SuppliedMaturityValuesAccordian",
    },
  },
  GrowthRates = {
    GrowthRateBasis: {
      Selector: ".GrowthRatesBasis_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
    },
    GrowthRateLow_Nominal: {
      Selector: ".GrowthRatesLow_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateLow",
    },
    GrowthRateMid_Nominal: {
      Selector: ".GrowthRatesMid_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateMid",
    },
    GrowthRateHigh_Nominal: {
      Selector: ".GrowthRatesHigh_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateHigh",
    },
    GrowthRateLow_InflationAdjusted: {
      Selector: ".GrowthRateLowInflationAdjusted_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateLow",
    },
    GrowthRateMid_InflationAdjusted: {
      Selector: ".GrowthRateMidInflationAdjusted_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateMid",
    },
    GrowthRateHigh_InflationAdjusted: {
      Selector: ".GrowthRateHighInflationAdjusted_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".GrowthRatesAccordian",
      AccordianName: "Growth Rates",
      XMLOverride: "GrowthRateHigh",
    },
  },
  //Some properties in here are the same as in other accordians
  ProductChages = {
    PC_FundCharge: {
      Selector: ".ProductChargesAccordian .FundCharge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".ProductChargesAccordian",
      AccordianName: "Product Charges",
    },
    PC_PlanCharge: {
      Selector: ".ProductChargesAccordian .PlanCharge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".ProductChargesAccordian",
      AccordianName: "Product Charges",
    },
    PC_PolicyFee: {
      Selector: ".ProductChargesAccordian .PolicyFee_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".ProductChargesAccordian",
      AccordianName: "Product Charges",
    },
    PC_AdviserCharge: {
      Selector: ".ProductChargesAccordian .AdviserCharge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".ProductChargesAccordian",
      AccordianName: "Product Charges",
    },
  },

  RegularWithdrawals = {
    RW_RegularWithdrawal: {
      Selector: ".RegularWithdrawal_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_Percentage: {
      Selector: ".RegularWithdrawalPercentage_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_Amount: {
      Selector: ".RegularWithdrawalAmount_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_Frequency: {
      Selector: ".RegularWithdrawalFrequency_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_PaidIn: {
      Selector: ".RegularWithdrawalPaidIn_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_Escalation: {
      Selector: ".RegularWithdrawalEscalationRate_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
    RW_OtherEscalation: {
      Selector: ".RegularWithdrawalEscalationRateOther_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".RegWithdrawalsAccordian",
      AccordianName: "Regular Withdrawals",
    },
  },

  OngoingContributions = {
    GrossPremium: {
      Selector: ".OngoingContsPremium_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
    GP_Frequency: {
      Selector: ".OngoingContsAccordian .OngoingContsType_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
    GP_Escalation: {
      Selector: ".OngoingContsAccordian .OngoingContsEscalationRate_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
    GP_EscalationOther: {
      Selector: ".OngoingContsAccordian .OngoingContsEscalationRateOther_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
    GP_IncreasingEvery: {
      Selector: ".OngoingContsAccordian .OngoingContsIncreasingEvery_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
    ClientExpenses: {
      Selector: ".ClientExpenses_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".OngoingContsAccordian",
      AccordianName: "Ongoing Contributions",
    },
  },
  PaidUpMaturityValues = {
    PUP_MaturityValueLow: {
      Selector: ".PUPMaturityValueLow_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".PUPAccordian",
      AccordianName: "Paid Up Maturity Values",
    },
    PUP_MaturityValueMid: {
      Selector: ".PUPMaturityValueMid_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".PUPAccordian",
      AccordianName: "Paid Up Maturity Values",
    },
    PUP_MaturityValueHigh: {
      Selector: ".PUPMaturityValueHigh_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".PUPAccordian",
      AccordianName: "Paid Up Maturity Values",
    },
    PUP_AsAtDate: {
      Selector: ".PupMaturityValuesAsAtDate_tooltip input",
      ddSelector:".PupMaturityValuesAsAtDate.day",
      mmSelector:".PupMaturityValuesAsAtDate.month",
      yyyySelector:".PupMaturityValuesAsAtDate.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".PUPAccordian",
      AccordianName: "Paid Up Maturity Values",
    },
  },
  AdditionalContributions = {
    AC_Single: {
      Selector: ".Drawdown_Single_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_Regular: {
      Selector: ".Drawdown_Regular_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_Frequency: {
      Selector: ".Drawdown_Frequency_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_Escalation: {
      Selector: ".Drawdown_Escalation_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_EscalationOther: {
      Selector: ".Drawdown_EscalationOther_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_Anniversary: {
      Selector: ".Drawdown_Anniversary_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_RegContsStop: {
      Selector: ".Drawdown_RegularContsStop_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
    AC_RegContsStopAge: {
      Selector: ".Drawdown_RegularContsStopAge_Relevant input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".AdditionalContsAccordian",
      AccordianName: "Additional Contributions",
    },
  },
  DefinedIncome = {
    DI_SafeguardedBenefits: {
      Selector: ".SafeguardedBenefits_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_SchemeNormalRetirementAge: {
      Selector: ".SchemeNRA_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_SchemeNormalRetirementAge: {
      Selector: ".SchemeNRA_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_BenefitsStartingAge: {
      Selector: ".BenefitsStartingAge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_DateLeftScheme: {
      Selector: ".DateLeftScheme_tooltip",
      ddSelector:".DateLeftScheme.day",
      mmSelector:".DateLeftScheme.month",
      yyyySelector:".DateLeftScheme.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_GrossAnnualIncome: {
      Selector: ".AnnualIncome_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalation: {
      Selector: ".IncomeEscalationRate_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalationOther: {
      Selector: ".IncomeEscalationRateOther_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalationStarting: {
      Selector: ".Starting_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalationStartingAge: {
      Selector: ".StartingAge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalationEnding: {
      Selector: ".Ending_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_IncomeEscalationEndingAge: {
      Selector: ".EndingAge_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_PCLSAtStart: {
      Selector: ".TaxFreeCashAtStart_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
    DI_PCLSPaid: {
      Selector: ".PCLSPaid_tooltip input",
      inputType: InputTypes.Input_Dropdown_ReadOnly,
      AccordianSelector: ".DefinedIncomeAccordian",
      AccordianName: "Defined Income",
    },
  },
  SchemeTransferDetails = {
    TD_TransferValue: {
      Selector: ".TransferValue_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_ValueAsAt: {
      Selector: ".TransferValueAsAt_tooltip input",
      ddSelector:".TransferValueAsAt.day",
      mmSelector:".TransferValueAsAt.month",
      yyyySelector:".TransferValueAsAt.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_RefinePCLSCommutationDetails: {
      Selector: ".RefinePCLSCommDetails",
      inputType: InputTypes.Input_Checkbox,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_PCLSbyCommutationNotAvailable: {
      Selector: ".PCLSCommNotAvailable",
      inputType: InputTypes.Input_Checkbox,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_CommutationFactor: {
      Selector: ".CommutationFactor_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_PCLSToTake: {
      Selector: ".PCLSToTake_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_AmountInTodaysTerms: {
      Selector: ".PCLSToTakeAmount_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_IncludeAdditionalVoluntaryContributions: {
      Selector: ".IncludeAdditionalVolConts",
      inputType: InputTypes.Input_Checkbox,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_AVCValue: {
      Selector: ".AVCV_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_AVCValueAsAt: {
      Selector: ".AVCValueAsAt_tooltip input",
      ddSelector:".AVCValueAsAt.day",
      mmSelector:".AVCValueAsAt.month",
      yyyySelector:".AVCValueAsAt.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_RefineDependantsDetails: {
      Selector: ".RefineDependantsDetails",
      inputType: InputTypes.Input_Checkbox,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_DependantsGender: {
      Selector: ".DependantsGender_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_DependantsDOB: {
      Selector: ".DependantsDOB_tooltip input",
      ddSelector:".DependantsDOB.day",
      mmSelector:".DependantsDOB.month",
      yyyySelector:".DependantsDOB.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_PreRetirement: {
      Selector: ".DependantsPensionPreNRA_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_PostRetirement: {
      Selector: ".DependantsPensionPostNRA_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_BasedOn: {
      Selector: ".SpousesPensionBasedOn_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_RefundOfContributionsForDeath: {
      Selector: ".RefundOfContributionsForDeathBenefits",
      inputType: InputTypes.Input_Checkbox,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_TotalMemberContributionstoScheme: {
      Selector: ".TotalMemberContributionsToScheme_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
    TD_RefundofContributionsInterestRate: {
      Selector: ".RefundOfContributionsInterestRate_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".SchemeTransferDetailsAccordian",
      AccordianName: "Scheme & Transfer Details",
    },
  },
  AssumptionsUsed = { 
    AU_GrowthRateToUse: {
      Selector: ".GrowthRateType_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_Rate: {
      Selector: ".GrowthRateToUse_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_Nominal: {
      Selector: ".Nominal_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_InflationAdjusted: {
      Selector: ".InflationAdjusted_tooltip input",
      inputType: InputTypes.Input_Integer,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_DateCeased: {
      Selector: ".DateCeasedContractingOut_tooltip input",
      ddSelector:".DateCeasedContractingOut.day",
      mmSelector:".DateCeasedContractingOut.month",
      yyyySelector:".DateCeasedContractingOut.year",
      inputType: InputTypes.Input_Date,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_IndexMonth: {
      Selector: ".IndexMonthForRevaluation_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
    AU_ERFApplied: {
      Selector: ".ERFAppliedToBenefitsRevaluedTo_tooltip input",
      inputType: InputTypes.Input_Dropdown,
      AccordianSelector: ".AssumptionsUsedAccordian",
      AccordianName: "Assumptions Used",
    },
  },
  AllCurrentPlanInputs = {
    ...BasicDetails,
    ...CurrentValue,
    ...DrawdownIncome,
    ...SuppliedMaturityValues,
    ...GrowthRates,
    ...ProductChages,
    ...RegularWithdrawals,
    ...OngoingContributions,
    ...PaidUpMaturityValues,
    ...AdditionalContributions,
    ...DefinedIncome,
    ...SchemeTransferDetails,
    ...AssumptionsUsed
  };
